### ISSUE TITLE
有没有使用到h265的example？

### ISSUE THREAD

**Issue by xujingzhou** [ilei131/android_webrtc_h265#1]
1. 请问该工程和下面代码有什么区别？
https://github.com/DrKLO/webrtc-google-h265

2. 生成so后，具体怎么个使用法才能使用到h265?  有没有具体的example提供一下？

3. 只支持h265编码，不支持解码么？

**Comment by ilei131** [comment]
1.我这个只是 Android 原生使用的 webrtc.jar 包(java 源码)和底层.so 库。
2.github 搜 android 原生 webrtc 例子就行。替换 webrtc.jar 包（或者java源码）和.so 库就行。
3.都支持（需要手机处理器支持 h265），看你客户端怎么协商或者服务端怎么处理了。
